pipeline {
    agent any
    tools {
        maven 'Maven_Home'
        dockerTool 'docker'
    }
    stages {
        stage("Build") {
            steps {
                git url: "https://github.com/FAnastasiaF/sbt-pddis", branch: "task5"
                 dir('task5') {
                  sh 'mvn clean install'
                }
            }
        }
        stage("SonarQube") {
            steps {
                withSonarQubeEnv("SonarQube") {
                    sh 'mvn clean package sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=password -f task5/pom.xml'
                }
            }
        }
        stage("Allure report") {
            steps {
                script {
                  allure includeProperties: false,
                          jdk: '',
                          results: [[path: 'target/reports/allure-results']]
                }
            }
        }

        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
          }

        stage('Deploy Prod') {
            steps {
              dir('task5') {
                sh 'docker run --name prod -d -p "8081:8080" task5';
              }
            }
        }
    }
}
