pipeline {
    agent any
    tools {
        maven 'Maven_Home'
        dockerTool 'docker'
    }
    stages {
        stage("Build") {
            steps {
                git url: "https://github.com/FAnastasiaF/sbt-pddis", branch: "task5"
                 dir('task5') {
                  sh 'mvn clean install'
                }
            }
            post {
                always {
                    junit(
                        testResults: 'task5/target/test-results/*.xml'
                    )
                }
            }
        }
        stage("SonarQube") {
            steps {
                withSonarQubeEnv("SonarQube") {
                    sh 'mvn clean package sonar:sonar -Dsonar.host.url=http://127.0.0.1:9000 -Dsonar.login=admin -Dsonar.password=password -X -e'
                }
            }
        }
        stage("Allure report") {
            steps {
                script {
                  allure includeProperties: false,
                          jdk: '',
                          results: [[path: 'target/reports/allure-results']]
                }
            }
        }

        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
          }

        stage("Deploy PROM") {
            steps {
                sh "ansible-playbook -i task5/inventory.yml task5/playbook.yml"
            }
        }
    }\
}